GenresReplace = {
    '18-Year-Old': ['18', '18 year', 'eighteen and...', 'eighteen', '18yo'],
    '19-Year-Old': ['19', 'nineteen'],
    '69 (Position)': ['69', '69 position', 'sixty-nine'],
    'All Natural': ['natural'],
    'Amateur': ['amateur pre auditions', 'amatuer'],
    'Anal': ['analed', 'anal sex', 'ass fucking'],
    'Anal Creampie': ['butt cum'],
    'Anal Fingering': ['ass fingering'],
    'Asian': ['asian amateur'],
    'Ass Eating': ['ass licking'],
    'Ass to Mouth': ['atm'],
    'Ass': ['booty', 'butt'],
    'Athletic Body': ['athlete', 'athletic', 'fit', 'fit body'],
    'Babysitter': ['nanny'],
    'Ball Gag': ['ballgagged'],
    'Ball Licking': ['ball lick', 'ball sucking'],
    'Bareback': ['no condom'],
    'Barely Legal': ['barely-legal'],
    'Bath': ['bathtub'],
    'BBC': ['big black cock'],
    'BBW': ['big beautiful women'],
    'Behind the Scenes': ['behind the scene', 'bts', 'behind-the-scenes', 'backstage'],
    'Big Butt': ['bib booty', 'big ass', 'big booty', 'big butts', 'fat ass', 'girl big ass'],
    'Big Dick': ['2 big cocks', 'big cock', 'big cocks', 'big dicks', 'big dicking'],
    'Big Natural Tits': ['big naturals'],
    'Big Nipples': ['big areolas'],
    'Big Tits': ['big boobs', 'bit tits', 'girl big tits', 'large tits', 'busty', 'big breasts', 'huge tits', 'huge boobs', 'bigger tits'],
    'Big Toys': ['big toy'],
    'Bikini': ['bikin'],
    'Blonde': ['blond', 'blond hair', 'blonde hair', 'blondes', 'interracial blonde'],
    'Blow Bang': ['blowbang'],
    'Blowjob': ['amateur blowjobs', 'bj', 'blow jobs', 'blow job', 'blowjob', 'blowjob (double)', 'blowjob (pov)', 'blowjob - double', 'blowjob - pov', 'blowjobs', 'sucking dick', 'cock sucking'],
    'Boots': ['boot'],
    'Bondage': ['bound', 'tied up'],
    'Boy-Boy-Boy-Girl': ['mmmf'],
    'Boy-Boy-Girl-Girl-Girl': ['fffmm'],
    'Boy-Boy-Girl-Girl': ['mmff'],
    'Boy-Boy-Girl': ['bbg', 'mmf', 'threesome bbg'],
    'Boy-Girl-Girl': ['2 girl bj', 'bgg', 'ffm', 'girl-girl-boy', 'threesome bgg', '2 Girls'],
    'Boy-Girl': ['boy girl', 'girl-boy', 'girl/boy'],
    'Braces': ['metal mouth'],
    'Bras & Panties': ['bras n panties'],
    'Breast Bondage': ['best bound breasts'],
    'Brother': ['bro'],
    'Brunette': ['brown hair', 'brunet', 'brunettes', 'brunette fucking', 'wet brunette'],
    'Bukkake': ['bukakke'],
    'Butt Plug': ['anal plug', 'buttplug'],
    'Camel Toe': ['camel toe pussy'],
    'Casting Couch': ['castingcouch'],
    'Caucasian': ['while', 'white', 'white girl', 'white girls', 'caucasian actress', 'white actress'],
    'CBT': ['death defying cbt'],
    'Chastity Play': ['chastity'],
    'Coeds': ['coed', 'college', 'university'],
    'Colored Hair': ['hair color', 'other hair color'],
    'Cop': ['police'],
    'Cosplay': ['costume', 'uniform'],
    'Couple': ['couples'],
    'Cowgirl (Position)': ['cow girl', 'cowgirl', 'cowgirl (pov)', 'cowgir', 'cowgril', 'cowirl'],
    'Creampie': ['cream pie', 'creampie compilation', 'cum in pussy', 'creampies'],
    'Creep': ['creepy'],
    'Cuckold': ['brutal cuckolding', 'cuckolding'],
    'Cum In Mouth': ['cum-in-mouth'],
    'Cum On Face': ['cum in face'],
    'Cum Swallowing': ['cum swallow', 'cum swallowers', 'swallow cum', 'swallowing cum'],
    'Cum Swap': ['cum swapping', 'cumswap'],
    'Cumming': ['cuming', 'cumming cum'],
    'Cumshot': ['cum shot', 'cum', 'cumshot cumming', 'cumshots'],
    'Curly Hair': ['curly'],
    'Curvy': ['curvy woman', 'thick', 'voluptuous'],
    'Deep Throat': ['deepthroat', 'deepthroating', 'deepthoat', 'deeothroat'],
    'Dildo': ['dildo play'],
    'Dirty Talk': ['dirty talking'],
    'Doggystyle (Position)': ['doggy style', 'doggystyle', 'doggy'],
    'Double Penetration (DP)': ['double penetration', 'double penetraton (dp)', 'dp'],
    'Ebony': ['african american', 'black', 'black girl', 'dark skin'],
    'Electro Play': ['electrical play', 'electrode punishments'],
    'European': ['euro', 'europe'],
    'Face Fucking': ['face fuck', 'facefucking', 'facefuck', 'mouth fucking', 'mouthfucking'],
    'Face Sitting': ['facesitting', 'queening'],
    'Facial': ['cumshot facial', 'facial (multiple)', 'facial (pov)', 'facial - pov', 'facials', 'open mouth facial', 'facialed'],
    'Fair Skin': ['pale', 'pale skin', 'whiteskin'],
    'Fake Tits': ['enhanced', 'enhanced tits', 'fake boobs', 'silicone tits'],
    'Family': ['fam', 'step family', 'step', 'steps'],
    'Father': ['dad'],
    'Feet': ['barefeet', 'foot'],
    'Fingering': ['finger fucking', 'fingering pussy', 'fingered'],
    'First Anal': ['first time anal'],
    'First Appearance': ['debut', 'first porn shoot', 'first time porn', 'model debut'],
    'First Interracial': ['first time ir'],
    'Fishnets': ['fishnet', 'fishnet stockings'],
    'Fisting': ['fisting\'s finest'],
    'Flat Chest': ['flat'],
    'Foot Job': ['footjob', 'footjobs'],
    'Fucking': ['fuck'],
    'Gangbang': ['gangbangs'],
    'Gaping': ['gape', 'gaped ass', 'gaping playlist', 'gaping asshole', 'gaped'],
    'Girl-Girl Pissing': ['girl girl pissing', 'lesbian pissing'],
    'Girl-Girl': ['girl girl', 'girl on girl', 'girl-on-girl', 'girl / girl'],
    'Girlfriend Experience': ['gfe'],
    'Glamorous': ['glamour'],
    'Group Sex': ['group', 'groupe sex'],
    'Gym': ['gym selfie porn', 'in the gym'],
    'Hairy Pussy': ['bush', 'hairy', 'hairy bush'],
    'Hand Job': ['handjob', 'handjob (pov)', 'handjob - pov', 'handjobs', 'hanjob'],
    'Hardcore': ['hardcore sex'],
    'Heterosexual': ['straight', 'straight porn'],
    'High Heels': ['heels'],
    'Holidays': ['holidayparty', 'holiday'],
    'Hood': ['hooded'],
    'Hotel Room': ['hotel'],
    'Housewife': ['housewives'],
    'Indoors': ['indoor'],
    'Interracial': ['ir', 'irpov', 'interracial mom4k'],
    'Interview': ['interviews'],
    'Jerk Off Instructions (JOI)': ['jerk off instruction', 'joi', 'joi games'],
    'Landing Strip': ['landing strip pussy'],
    'Latex': ['latex darlings'],
    'Latina': ['latinas'],
    'Lesbian': ['lesbians'],
    'Lezdom': ['lesbian domination'],
    'Lingerie': ['lenceria'],
    'Lube': ['lub', 'lube', 'lubed'],
    'Maid': ['maid fetish'],
    'Mask': ['masks'],
    'Massage': ['body massage'],
    'Masturbation': ['masturbacion', 'masturbating', 'masturbate'],
    'Medical Fetish': ['doctor', 'doctor/nurse', 'nurse', 'nurse play'],
    'Medium Tits': ['medium boobs'],
    'MILF & Mature': ['mature & milf'],
    'MILF': ['milfs'],
    'Mini Skirt': ['miniskirts'],
    'Missionary (Position)': ['missionary', 'missionary (pov)', 'missionary - pov'],
    'Model': ['modelo'],
    'Mother': ['mom', 'moms'],
    'Muscular': ['muscle'],
    'Natural Tits': ['natural boobs', 'real tits', 'natural breasts', 'real boobs', 'real breasts'],
    'Nerd': ['nerdy'],
    'Nude': ['completely naked', 'naked'],
    'Office Setting': ['office'],
    'Oil': ['babyoil', 'oiled', 'oil / lotion', 'oily', 'oiled up', 'oil oiled', 'oily sex'],
    'Older/Younger': ['older / younger'],
    'One-On-One': ['1 on 1'],
    'Oral Sex': ['oral'],
    'Orgasms': ['amazing orgasms', 'orgasm'],
    'Orgy': ['four or more'],
    'Outdoor Sex': ['outdoors'],
    'Outdoors': ['outdoor'],
    'Paddle': ['paddling'],
    'Panties': ['braguitas'],
    'Passion': ['passionate'],
    'Pantyhose & Stockings': ['black stockings', 'nude stockings', 'nylons stockings', 'pantyhose', 'pantyhose / stockings', 'pantyhose footjobs', 'stocking', 'stockings'],
    'Petite': ['skinny', 'little', 'petiet', 'small', 'slim', 'tiny'],
    'Pierced Nipples': ['pierced nipple'],
    'Piercing': ['piercings'],
    'Pile Driver': ['pile driving'],
    'Piss Play': ['pee', 'pissing'],
    'Pool': ['poolparty'],
    'Pornstar Experience': ['pse'],
    'Pornstar': ['pornstars', 'porn star'],
    'POV': ['femdom pov', 'p.o.v.', 'point of view'],
    'Public Sex': ['public'],
    'Pussy Eating': ['cunilingus', 'pussy lick', 'pussy licking', 'licking pussy', 'eating pussy', 'pussy-eating'],
    'Real Estate': ['realestate'],
    'Reality Porn': ['reality'],
    'Redhead': ['red head', 'red heads'],
    'Reverse Cowgirl (Position)': ['cowgirl - pov', 'reverse cow girl', 'reverse cowgirl', 'reverse cowgirl (pov)', 'reverse cowgril', 'reeverse cowgirl'],
    'Rim Job': ['rimjob', 'rimming'],
    'Schoolgirl Outfit': ['school girl', 'schoolgirl'],
    'Sci-Fi and Fantasy': ['sci fi'],
    'Self Sucking': ['self-sucking'],
    'Sex': ['sexo'],
    'Shaven Pussy': ['bald pussy', 'shaved', 'shaved pussy'],
    'Shoe Fetish': ['shoeplay', 'sneaker fetish'],
    'Sissification': ['sissy training course'],
    'Sister': ['sis'],
    'Skirt': ['skirts'],
    'Small Ass': ['small booty', 'small butt'],
    'Small Tits': ['small boobs', 'tiny breasts', 'tiny tits', 'tiny boobs', 'small breasts', 'little boobs', 'little breasts', 'little tits'],
    'Soaked': ['soaking'],
    'Soapy': ['soaped', 'soap', 'suds'],
    'Solo': ['solo action', 'solo masturbation', 'solo sex'],
    'Spooning': ['spoon'],
    'Spying': ['spy'],
    'Squirting': ['squirt', 'top squirting videos', 'squirter'],
    'St. Patrick\'s Day': ['st patrick\'s day', 'st.patricks', 'st patricks day'],
    'Step Brother': ['stepbro', 'stepbrother'],
    'Step Daughter': ['stepdaughter'],
    'Step Father': ['stepdad'],
    'Step Mom': ['stepmom', 'stepmother', 'step mother'],
    'Step Sister': ['ste sister', 'step sis', 'step siter', 'step-sister', 'stepsis', 'stepsister'],
    'Step Son': ['stepson'],
    'Strap-On': ['pov strapon', 'strap on'],
    'Strip Club': ['stripclub'],
    'Striptease': ['strip tease'],
    'Swallowing': ['amateur swallow', 'swallow'],
    'Tan Lines': ['tanlines'],
    'Tan': ['tanned skin'],
    'Tattoo': ['tattoo girl', 'tattooed', 'tattoos', 'inked'],
    'Tattoos & Piercing': ['tats / piercing'],
    'Teacher Fetish': ['teacher'],
    'Tease': ['teasing'],
    'Tease and Denial': ['tease & denial'],
    'Teen': ['18+ teen', 'bad teens punished', 'teen porn', 'teen role', 'teens'],
    'Thong': ['thongs'],
    'Threesome': ['2 on 1', '2-on-1', '2on1', '3 way', '3some', 'threesomes', '3way', 'threeway'],
    'Throat Fucking': ['Throat Fuck'],
    'Tit Sucking': ['tit suck', 'tit sucking', 'titty sucking', 'tit-sucking'],
    'Titty Fuck': ['tit fuck', 'tit fucking', 'titty fucking', 'tittyfuck', 'tittyfuck (pov)', 'tittyfuck - pov', 'titfuck', 'titjob', 'titsjob', 'tit-fucking'],
    'Toys': ['sex toys', 'toy insertions', 'toy'],
    'Transsexual': ['trans', 'transexual', 'ts'],
    'Tribbing': ['scissoring'],
    'Trimmed Pussy': ['trimmed', 'trimmed bush', 'groomed pussy'],
    'Twerking': ['tweking'],
    'Uncircumcised': ['uncut dicks'],
    'Uniform': ['uniforms'],
    'Valentine\'s Day': ['valentines day', 'valentine'],
    'Video Game': ['videogame'],
    'Whipping': ['whip', 'whipped'],
}

GenresSkip = [
    '18+ teens',
    '18+teens',
    '4k',
    '60p',
    'acworthy',
    'adalind grey',
    'alli addison',
    'anthony pierce',
    'april showers',
    'april',
    'austin pierce',
    'babe',
    'babes',
    'bccpie',
    'beaverday',
    'big tre',
    'bobby beefcakes',
    'bonus',
    'brad sterling',
    'brian o\'mally',
    'brick danger',
    'brickzilla',
    'brock cooper',
    'brock copper',
    'bruce venture',
    'c4k',
    'chad white',
    'charlie dean',
    'connor kennedy',
    'damion dayski',
    'danny mountain',
    'darel deeps',
    'david lee',
    'davon drake',
    'daylight savings',
    'desert apocalypse',
    'destruction',
    'duncan saint',
    'episode',
    'exclusive',
    'extra update',
    'faces of pain',
    'facial4k',
    'feel me',
    'first',
    'get sprung',
    'gonzo',
    'grey',
    'hd videos',
    'heavymetal',
    'irreconcilable slut',
    'isaiah maxwell',
    'isiah maxwell',
    'jack rippher',
    'jaime jett',
    'jay bangher',
    'jay romero',
    'jmac',
    'johnny castle',
    'johnny the kid',
    'johnny the kidd',
    'jon jon',
    'jonathan jordan',
    'jovan jordan',
    'keiran',
    'kyle mason',
    'kyle shay',
    'lana rhoads',
    'lily larmiar',
    'little runaway',
    'liza rowwe',
    'marika hase',
    'mia collinsm my',
    'mr. cummings',
    'mvft',
    'my',
    'nade nasty',
    'of',
    'oliver faze',
    'peter green',
    'photos',
    'point',
    'pornplus',
    'pornpros',
    'preston parker',
    'public disgrace\'s best',
    'quinton james',
    'realexgirlfriend',
    'rebel lynn',
    'ricky spanish',
    'rion king',
    'rion pierce oliver',
    'ryan driller',
    'ryan mclane',
    'sally squirts',
    'sam shock',
    'show less',
    'show more',
    'site member',
    'smart',
    'spring cleaning',
    't4k',
    'the pope',
    'time',
    'tj cummings',
    'tommy gunn',
    'tony rubino',
    'tony',
    'twistys hard',
    'tyler cruise',
    'tyler steel',
    'tyler steele',
    'van styles',
    'van wylde',
    'very',
    'view',
    'will pounder',
    'will tile',
    'workitout',
    'wow girls special',
    'yes, mistress',
]

GenresPartialSkip = [
    '1080p',
    '5k',
    '60fps',
    'aprilfools',
    'chibbles',
    'folsom',
    'hd',
]
